### ISSUE TITLE
Example of how to test this

### ISSUE THREAD

**Issue by jcscottiii** [robbiev/dilemma#1]
Would be helpful and powerful to see an example of how a developer could send key pushes in tests to test the user experience of their terminal app.

**Comment by robbiev** [comment]
While it would be an interesting exercise I don't think this is worth the trouble. If you want to test code that uses this library I suggest you create an abstraction for testing, for example:

``` go
type dilemma interface {
    Prompt(config dilemma.Config) (string, dilemma.Key, error)
}

type testDilemma struct {
    selectedOption string
}

func (d testDilemma) Prompt(config dilemma.Config) (string, dilemma.Key, error) {
    return d.selectedOption, dilemma.Empty, nil
}
```

I didn't try to compile this but you get the idea.
